title: Thomas Robinson

future: true
baseurl: ""
url: https://thomasr.me
locale: en_GB

collections:
  projects:
    layout: default
    output: true

twitter: itsmeimtom
github: itsmeimtom
keybase: itsmeimtom
lfm: itsmeimtom
lin: thomas--r
flickr: "193606210@N05"

permalink: /:year/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"

sass:
  sass_dir: assets/style
  style: compressed

highlighter: rouge

compress_html:
  blanklines: true
  ignore:
    envs: ["development"]

plugins:
  # - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-archives
  - jekyll-last-modified-at
  - jekyll-sitemap

exclude:
  - vercel.json
  
feed:
  path: /blog/feed.xml
  excerpt_only: true
  posts_limit: 0

jekyll-mentions:
  base_url: https://twitter.com

jekyll-archives:
  layout: post-archive
  enabled:
    - categories
    - year
  permalinks:
    year: '/:year/'
    category: "/blog/archive/:name/"
