title: Thomas Robinson

future: true
baseurl: ""
url: https://thomasr.me
locale: en_GB

collections:
  projects:
    layout: default
    output: true

twitter: itsmeimtom
github: itsmeimtom
keybase: itsmeimtom
lfm: itsmeimtom
lin: thomasr-me
flickr: "193606210@N05"

permalink: /:year/:title/

sass:
  sass_dir: assets/style
  style: compressed

highlighter: rouge

compress_html:
  blanklines: true
  ignore:
    envs: ["development"]

plugins:
  # - jekyll-redirect-from
  # - jekyll-mentions
  # - jekyll-archives
  - jekyll-last-modified-at
  - jekyll-sitemap

exclude:
  - vercel.json