title: ThomasR.me

future: true
baseurl: ""
url: https://thomasr.me
locale: en_GB

permalink: /:title/

sass:
  sass_dir: assets/style
  style: compressed

highlighter: rouge

compress_html:
  blanklines: true
  ignore:
    envs: ["development"]

plugins:
  # - jekyll-redirect-from
  # - jekyll-mentions
  # - jekyll-archives
  # - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-sitemap

exclude:
  - vercel.json