title: trobinson.me

future: true
baseurl: ""
url: https://trobinson.me
locale: en_GB

collections:
  projects:
    output: false

twitter: itsmeimtom
github: itsmeimtom
keybase: itsmeimtom
flickr: "193606210@N05"
youtube: dnomaid

permalink: /:year/:title/

sass:
  sass_dir: css
  style: compressed

highlighter: rouge

compress_html:
  clippings: all
  comments: all
  blanklines: false

plugins:
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-archives
  - jekyll-last-modified-at
  - jekyll-sitemap
  
feed:
  path: /blog/feed.xml
  excerpt_only: true
  posts_limit: 0

jekyll-mentions:
  base_url: https://twitter.com

jekyll-archives:
  layout: post_archive
  enabled:
    - categories
    - year
  permalinks:
    year: '/:year/'
    category: "/blog/archive/:name/"